#ifndef KILOBOTOHCLIB_GLOBAL_H
#define KILOBOTOHCLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KILOBOTOHCLIB_LIBRARY)
#  define KILOBOTOHCLIB_EXPORT Q_DECL_EXPORT
#else
#  define KILOBOTOHCLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // KILOBOTOHCLIB_GLOBAL_H
